### ISSUE TITLE
Build fails for Android on Cordova 6.3.1

### ISSUE THREAD

**Issue by bsides** [NeutrinosPlatform/cordova-plugin-document-scanner#2]
It asks for `cordova-android >= 6.3` and Cordova 6.3.1 has `cordova-android 5.2.2`. 
In the plugin documentation it reads `This requires cordova 5.0+` so I would like to keep using Cordova 6.3.1, is there any way to fix this?

Thank you!

**Comment by ChrisTomAlx** [comment]
Unfortunately, You will need a minimum cordova version of 7.1.0 for this to work. Correcting the documentation now. 

Thank you for bringing this to our attention.

**Comment by bsides** [comment]
Thanks for answering!

I'm just curious if I could make it work on `cordova-android 5.2.2`. The reason is that I have many plugins that doesn't work in cordova 7+ so I'd really like to stay there. Is there a special API call that wouldn't make this work in `cordova-android 5.2.2`?

Thanks again!

**Comment by ChrisTomAlx** [comment]
I'm sorry. Right now we don't have any such special API calls. 

Although if you would like to play around with it using  cordova-android 5.2.2 all you need to do is download it and do the following :-
1) Change the cordovaDependencies minimum version for android in package.json.
2) Change the minimum android version number in the cordova-android engine tag within plugin.xml.
3) After you unzip the downloaded file and do steps (1) & (2)  you can add the plugin to your cordova project using something like this : 
    cordova plugin add <folder where your plugin.xml exists>
    eg :- cordova plugin add D:\cordova-plugin-document-scanner-master

I hope this helps :)

**Comment by Karanveer-logiciel** [comment]
I am facing same problem to create build on cordova 6.1.2 

error show the following content:
----------------------------------------------------------------------
java.lang.IllegalStateException: buildToolsVersion is not specified.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:645)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)...

Totally enable to create a build after install this plugin. Any solution??

**Comment by ChrisTomAlx** [comment]
@Karanveer-logiciel The plugin requires a min cordova ver of 6.4.0 as specified in the documentation.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
