### ISSUE TITLE
Android: App crashes after taking Photo (Unable to resume activity)

### ISSUE THREAD

**Issue by bendspoons** [NeutrinosPlatform/cordova-plugin-document-scanner#69]
After my Update to Android 10 (Huawei mate 20) the Document Scanner crashes after ive taken a Photo. The same App, running on a Huawei P20 with Android 9 works well.

Installed Plugin with target and build SDK to 29, Android@7.1.4

Error
`2020-02-13 22:37:37.742 5876-5876/com.app.documentscanner E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.documentscanner, PID: 5876
    java.lang.RuntimeException: Unable to resume activity {com.app.documentscanner/com.app.documentscanner.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=99, result=0, data=null} to activity {com.app.documentscanner/com.app.documentscanner.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4767)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4810)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=99, result=0, data=null} to activity {com.app.documentscanner/com.app.documentscanner.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5449)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4754)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4810) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
        at com.neutrinos.plugin.Scan.onActivityResult(Scan.java:107)
        at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:159)
        at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:359)
        at android.app.Activity.dispatchActivityResult(Activity.java:8393)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5442)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4754) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4810) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
2020-02-13 22:37:37.773 5876-5876/com.app.documentscanner I/Process: Sending signal. PID: 5876 SIG: 9
`

**Comment by bendspoons** [comment]
A bit more info:

`2020-02-13 23:12:31.669 13614-13614/com.app.documentscanner D/ActivityThread: add activity client record, r= ActivityRecord{dc0ce4d token=android.os.BinderProxy@ae1139c {com.app.documentscanner/com.app.documentscanner.MainActivity}} token= android.os.BinderProxy@ae1139c
2020-02-13 23:12:31.671 13614-13614/com.app.documentscanner D/CordovaActivity: Started the activity.
2020-02-13 23:12:31.676 13614-13614/com.app.documentscanner D/CordovaActivity: Incoming Result. Request code = 99
2020-02-13 23:12:31.678 13614-13614/com.app.documentscanner D/CordovaInterfaceImpl: Sending activity result to plugin
2020-02-13 23:12:31.679 13614-13614/com.app.documentscanner I/BlockMonitor: dispatchingThrewException In MainThread
2020-02-13 23:12:31.679 13614-13614/com.app.documentscanner D/AndroidRuntime: Shutting down VM
2020-02-13 23:12:31.680 13614-13614/com.app.documentscanner I/QarthLog: [PatchStore] createDisableExceptionQarthFile
2020-02-13 23:12:31.680 13614-13614/com.app.documentscanner I/QarthLog: [PatchStore] create disable file for com.app.documentscanner uid is 10618`

I think it has something to do with the Resukt and the request code. When i uncommented Line 108 in Scan.java

`this.callbackContext.error("Incorrect result or user canceled the action.");`

The app still crashes, but is reopened from start.

**Comment by bendspoons** [comment]
After some slightly deeper digging, i encountered this Info:

`2020-02-13 23:27:34.008 18681-18681/com.app.documentscanner W/MediaStore: Failed to insert image
    java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at android.provider.MediaStore$PendingSession.<init>(MediaStore.java:765)
        at android.provider.MediaStore.openPending(MediaStore.java:639)
        at android.provider.MediaStore$Images$Media.insertImage(MediaStore.java:1796)
        at com.scanlibrary.Utils.getUri(Utils.java:23)
        at com.scanlibrary.PickImageFragment.postImagePick(PickImageFragment.java:373)
        at com.scanlibrary.PickImageFragment.onActivityResult(PickImageFragment.java:368)
        at android.app.Activity.dispatchActivityResult(Activity.java:8420)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5442)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5490)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`

Som maybe it has something to do with the Android Scanner library itself?

**Comment by bendspoons** [comment]
Is Android 10 (Q) so rare, or am i the only one experiencing this Error?!??

**Comment by ChrisTomAlx** [comment]
Hey @bendspoons 
Sorry I could not respond earlier.
If you would like to contribute, then you can make the required changes in the [scanlibrary](https://github.com/NeutrinosPlatform/scanlibrary/tree/master/library/src/main/java/com/scanlibrary).

And to make sure you are using your fork of the scan library, make sure you change the build.gradle  (similar to [this](https://github.com/NeutrinosPlatform/cordova-plugin-document-scanner/commit/4ffc458fd72d0ee117c1ac75392e274a79c578c4)) in your fork of the plugin to use SNAPSHOT and also change the repo it targets (Yours if you are planning to fork).

I will try and get on this as and when time permits, but for now all I can do is point you in the right direction.

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
This issue has now been fixed in plugin version 4.2.5
Sorry about the delay

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by macsupport** [comment]
Still crashes with v4.2.5. I get "incorrect result or user canceled action" every time.
        
        function successCallback(imageData) {
        var image = document.getElementById('myImage');
         image.src = "data:image/jpeg;base64," + imageData;
       }

        function errorCallback(message) {
        alert('Failed because: ' + message);
       }
       scan.scanDoc(successCallback, errorCallback, {returnBase64 : true});
